# Generated by Django 3.0.2 on 2020-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200321_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/user_avatar.JPG', upload_to='images/%Y'),
        ),
    ]
